### ISSUE TITLE
Docs: Uploading Recordings of Serial Communication?

### ISSUE THREAD

**Issue by nerilex** [bosb/KL9005s#1]
Hello,

can you upload your recordings of the communication between the reader and the windows software?

I still could not get the SDK from the seller, so I'm currently lacking the tools to create recordings myself. ¯\\_(ツ)_/¯

But at least I now know what kind of UHF RFID reader is sitting on my desk :-).

**Comment by bosb** [comment]
Sorry, but there is no more information in to get than it is extracted to the python file, there you find the commands from the logs.
...
x# | Time | Function | Direction | Status | Data | Data (chars) | Data length | Req. length | Port | Comments
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 27/08/2019 20:17:39 | IRP_MJ_WRITE | UP | STATUS_SUCCESS | 0a ff 03 20 00 d4 | .ˇ. .‘ | 6 |   | COM7 |  
3 | 27/08/2019 20:17:39 | IRP_MJ_READ | UP | STATUS_SUCCESS | 0b ff 02 | .ˇ. | 3 |   | COM7 |  
5 | 27/08/2019 20:17:39 | IRP_MJ_READ | UP | STATUS_SUCCESS | 00 f4 | .Ù | 2 |   | COM7 |  
...
137 | 27/08/2019 20:30:58 | IRP_MJ_READ | UP | STATUS_SUCCESS | 0b ff 02 | .ˇ. | 3 |   | COM7 |  
139 | 27/08/2019 20:30:58 | IRP_MJ_READ | UP | STATUS_SUCCESS | 05 ef | .Ô | 2 |   | COM7 |  
141 | 27/08/2019 20:31:18 | IRP_MJ_WRITE | UP | STATUS_SUCCESS | 0a ff 05 85 01 00 01 6b | .ˇ.Ö...k | 8 |   | COM7 |  
143 | 27/08/2019 20:31:18 | IRP_MJ_READ | UP | STATUS_SUCCESS | 0b ff 05 | .ˇ. | 3 |   | COM7 |  
145 | 27/08/2019 20:31:18 | IRP_MJ_READ | UP | STATUS_SUCCESS | 00 00 e7 64 a6 | ..Ád¶ | 5 |   | COM7 |  
147 | 27/08/2019 20:31:52 | IRP_MJ_WRITE | UP | STATUS_SUCCESS | 0a ff 05 85 01 00 02 6a | .ˇ.Ö...j | 8 |   | COM7 |  
149 | 27/08/2019 20:31:52 | IRP_MJ_READ | UP | STATUS_SUCCESS | 0b ff 07 | .ˇ. | 3 |   | COM7 |  
151 | 27/08/2019 20:31:52 | IRP_MJ_READ | UP | STATUS_SUCCESS | 00 00 e7 64 30 00 74 | ..Ád0.t | 7 |   | COM7 |  
153 | 27/08/2019 20:32:34 | IRP_MJ_WRITE | UP | STATUS_SUCCESS | 0a ff 05 85 01 00 03 69 | .ˇ.Ö...i | 8 |   | COM7
...
